ALTER TABLE users ALTER COLUMN id RESTART WITH 1;
ALTER TABLE todos ALTER COLUMN id RESTART WITH 1;
ALTER TABLE projects ALTER COLUMN id RESTART WITH 1;
ALTER TABLE labels ALTER COLUMN id RESTART WITH 1;
