ALTER TABLE "user" ALTER COLUMN id RESTART WITH 1;
ALTER TABLE todo ALTER COLUMN id RESTART WITH 1;
ALTER TABLE project ALTER COLUMN id RESTART WITH 1;
ALTER TABLE label ALTER COLUMN id RESTART WITH 1;
