spring:
  datasource:
    url: jdbc:h2:mem:db;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    # jdbc:h2:file:~
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      encoding: UTF-8
      mode: embedded
      schema-locations: classpath:/schema-h2.sql
      # data-locations: classpath:/data.sql
  h2:
    console:
      enabled: true
      path: /h2
